version: "3.8"

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: maria-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"

  web-service:
    container_name: srping-boot
    build: .
    image: bekhub/spring-university
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/workspace/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/university?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always